title: Jacob Thorpe's Portfolio
description: A webpage to showcase what I've made
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme